import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
	{
	  _id: uuid(),
	  title: "Stylo Plume Classique",
	  author: "par Bic",
	  price: "30",
	  previousPrice: "40",
	  image: "/assets/productImages/styloplume.webp",
	  categoryName: "écriture",
	  rating: 4.5,
	},
	{
	  _id: uuid(),
	  title: "Cahier à Spirale A4",
	  author: "par Oxford",
	  price: "25",
	  previousPrice: "30",
	  image: "/assets/productImages/cahierspirale.webp",
	  categoryName: "scolaire",
	  rating: 4.2,
	},
	{
	  _id: uuid(),
	  title: "Boîte d'Archive",
	  author: "par Elba",
	  price: "50",
	  previousPrice: "60",
	  image: "/assets/productImages/boitearchive.webp",
	  categoryName: "organisation",
	  rating: 3.8,
	},
	{
	  _id: uuid(),
	  title: "Crayons de Couleur",
	  author: "par Crayola",
	  price: "20",
	  previousPrice: "25",
	  image: "/assets/productImages/crayonscouleur.webp",
	  categoryName: "créativité",
	  rating: 4.7,
	},
	{
	  _id: uuid(),
	  title: "Trousse Scolaire",
	  author: "par Kipling",
	  price: "45",
	  previousPrice: "55",
	  image: "/assets/productImages/troussescolaire.webp",
	  categoryName: "scolaire",
	  rating: 4.3,
	},
	{
	  _id: uuid(),
	  title: "Stylos Gel Pack de 10",
	  author: "par Pilot",
	  price: "35",
	  previousPrice: "40",
	  image: "/assets/productImages/stylosgel.webp",
	  categoryName: "écriture",
	  rating: 4.6,
	},
	{
	  _id: uuid(),
	  title: "Pinceaux de Peinture",
	  author: "par Lefranc & Bourgeois",
	  price: "60",
	  previousPrice: "70",
	  image: "/assets/productImages/pinceauxpeinture.webp",
	  categoryName: "créativité",
	  rating: 4.8,
	},
	{
	  _id: uuid(),
	  title: "Classeurs à Levier",
	  author: "par Esselte",
	  price: "40",
	  previousPrice: "50",
	  image: "/assets/productImages/classeuralevier.webp",
	  categoryName: "organisation",
	  rating: 4.0,
	},
	{
	  _id: uuid(),
	  title: "Feuilles de Dessin A3",
	  author: "par Canson",
	  price: "20",
	  previousPrice: "25",
	  image: "/assets/productImages/feuillesdessin.webp",
	  categoryName: "créativité",
	  rating: 4.5,
	},
	{
	  _id: uuid(),
	  title: "Carnet de Notes",
	  author: "par Moleskine",
	  price: "50",
	  previousPrice: "60",
	  image: "/assets/productImages/carnetnotes.webp",
	  categoryName: "scolaire",
	  rating: 4.9,
	},
	{
	  _id: uuid(),
	  title: "Marqueurs Permanent",
	  author: "par Sharpie",
	  price: "25",
	  previousPrice: "30",
	  image: "/assets/productImages/marqueurspermanent.webp",
	  categoryName: "écriture",
	  rating: 4.7,
	},
	{
	  _id: uuid(),
	  title: "Pochette de Chemises",
	  author: "par Exacompta",
	  price: "30",
	  previousPrice: "35",
	  image: "/assets/productImages/pochettechemises.webp",
	  categoryName: "organisation",
	  rating: 4.4,
	},
	{
	  _id: uuid(),
	  title: "Feutres Lavables",
	  author: "par Stabilo",
	  price: "40",
	  previousPrice: "45",
	  image: "/assets/productImages/feutreslavables.webp",
	  categoryName: "créativité",
	  rating: 4.6,
	},
	{
	  _id: uuid(),
	  title: "Ramette de Papier A4",
	  author: "par Clairefontaine",
	  price: "10",
	  previousPrice: "15",
	  image: "/assets/productImages/ramettepapier.webp",
	  categoryName: "scolaire",
	  rating: 4.2,
	},
  ];
